### ISSUE TITLE
几个小建议

### ISSUE THREAD

**Issue by kjsc0310** [444136347/hx-navigation#1]
大佬开源的导航很不错，非常奈斯
有几个小建议
1、分类加密功能。可在界面设置一个输入密码的入口，输入后可展示隐藏的分类
2、后台增加导入浏览器书签功能和批量导入网址、logo链接功能。可设置某种导入格式，格式里面包含名称、网址、说明、logo链接等信息
3、如第二条，可实现logo链接模式，非必须本地上传
4、增加首页弹窗提醒功能
5、数据备份、迁移功能

**Comment by 444136347** [comment]
感谢建议，后续功能修改可能考虑
